/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Absence {
  'id' : AbsenceId,
  'status' : AbsenceStatus,
  'absenceTypeId' : AbsenceTypeId,
  'dateTo' : string,
  'ganztaetig' : boolean,
  'approvedBy' : [] | [Principal],
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'employeeId' : EmployeeId,
  'resetReason' : [] | [string],
  'rejectionComment' : [] | [string],
  'dateFrom' : string,
  'dauer' : bigint,
  'companyId' : CompanyId,
}
export interface AbsenceFilter {
  'status' : [] | [AbsenceStatus],
  'absenceTypeId' : [] | [AbsenceTypeId],
  'dateTo' : [] | [string],
  'employeeId' : [] | [EmployeeId],
  'dateFrom' : [] | [string],
}
export type AbsenceId = bigint;
export type AbsenceStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AbsenceType {
  'id' : AbsenceTypeId,
  'aktiv' : boolean,
  'name' : string,
  'requiresApproval' : boolean,
  'compensated' : boolean,
  'companyId' : CompanyId,
}
export type AbsenceTypeId = bigint;
export interface AuditEntry {
  'id' : bigint,
  'oldStatus' : string,
  'action' : string,
  'changedBy' : Principal,
  'timestamp' : Time,
  'targetType' : string,
  'newStatus' : string,
  'targetId' : bigint,
  'previousApprovedBy' : [] | [Principal],
  'reason' : [] | [string],
}
export interface CalendarData {
  'absences' : Array<Absence>,
  'expenses' : Array<Expense>,
  'timeEntries' : Array<TimeEntry>,
}
export interface Company {
  'id' : CompanyId,
  'taxId' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'logoUrl' : [] | [string],
  'address' : [] | [string],
}
export type CompanyId = bigint;
export interface CompanySettings {
  'timezone' : string,
  'approvalRequired' : boolean,
  'allowExpiredVacationBalance' : boolean,
  'emailNewVacationRequest' : boolean,
  'emailOnApproval' : boolean,
  'vacationCarryoverDays' : bigint,
  'maxVacationDays' : bigint,
  'companyId' : CompanyId,
}
export interface CreateAbsenceInput {
  'absenceTypeId' : AbsenceTypeId,
  'dateTo' : string,
  'ganztaetig' : boolean,
  'description' : [] | [string],
  'dateFrom' : string,
  'dauer' : bigint,
}
export interface CreateAbsenceTypeInput {
  'aktiv' : [] | [boolean],
  'name' : string,
  'requiresApproval' : boolean,
  'compensated' : boolean,
}
export interface CreateCustomerInput {
  'rechnungsadresse' : [] | [Rechnungsadresse],
  'contact' : [] | [string],
  'aktiv' : [] | [boolean],
  'name' : string,
  'zeiterfassungsart' : [] | [KundeZeiterfassungsart],
  'kundennummer' : [] | [string],
  'notes' : [] | [string],
  'beschreibung' : [] | [string],
  'waehrung' : [] | [string],
}
export interface CreateEmployeeInput {
  'ort' : [] | [string],
  'plz' : [] | [string],
  'weeklyHoursTarget' : number,
  'postfach' : [] | [string],
  'land' : [] | [string],
  'role' : Role,
  'email' : string,
  'geburtsdatum' : [] | [bigint],
  'employmentType' : EmploymentType,
  'adresseZusatz1' : [] | [string],
  'adresseZusatz2' : [] | [string],
  'lastName' : string,
  'strasse' : [] | [string],
  'startDate' : string,
  'firstName' : string,
}
export interface CreateEmploymentInput {
  'bis' : [] | [bigint],
  'von' : bigint,
  'pensum' : number,
  'feiertagsberechnungsart' : FeiertagsberechnungsartType,
  'stundenDi' : bigint,
  'stundenDo' : bigint,
  'stundenFr' : bigint,
  'stundenMi' : bigint,
  'stundenMo' : bigint,
  'stundenSa' : bigint,
  'stundenSo' : bigint,
  'funktion' : string,
}
export interface CreateExpenseInput {
  'date' : string,
  'description' : string,
  'billableCHF' : number,
  'reimbursementCHF' : number,
  'expenseTypeId' : ExpenseTypeId,
  'receiptBlobId' : [] | [string],
}
export interface CreateExpenseTypeInput {
  'aktiv' : [] | [boolean],
  'name' : string,
  'billable' : boolean,
  'reimbursable' : boolean,
}
export interface CreateHolidayInput {
  'ganztaegig' : [] | [boolean],
  'date' : string,
  'name' : string,
}
export interface CreateProjectInput {
  'status' : [] | [ProjectStatus],
  'erfassungsart' : [] | [Erfassungsart],
  'code' : string,
  'billableRate' : number,
  'name' : string,
  'customerId' : CustomerId,
  'kurzbezeichnung' : string,
  'projektleiter' : [] | [EmployeeId],
}
export interface CreateServiceTypeInput {
  'defaultRate' : number,
  'aktiv' : [] | [boolean],
  'name' : string,
  'billable' : boolean,
}
export interface CreateTimeBalanceCorrectionInput {
  'typ' : { 'gutschrift' : null } |
    { 'reduktion' : null },
  'ueberzeit' : bigint,
  'bemerkung' : string,
  'wirkungsdatum' : bigint,
  'dauer' : bigint,
}
export interface CreateTimeEntryInput {
  'bis' : [] | [string],
  'von' : [] | [string],
  'hours' : number,
  'date' : string,
  'description' : string,
  'billable' : boolean,
  'projectId' : ProjectId,
  'serviceTypeId' : ServiceTypeId,
}
export interface CreateVacationBalanceInput {
  'verfallsdatum' : [] | [bigint],
  'kalenderjahr' : bigint,
  'dauer' : bigint,
}
export interface Customer {
  'id' : CustomerId,
  'rechnungsadresse' : [] | [Rechnungsadresse],
  'contact' : [] | [string],
  'aktiv' : boolean,
  'name' : string,
  'zeiterfassungsart' : KundeZeiterfassungsart,
  'kundennummer' : [] | [string],
  'notes' : [] | [string],
  'beschreibung' : [] | [string],
  'waehrung' : string,
  'companyId' : CompanyId,
}
export type CustomerId = bigint;
export interface DashboardStats {
  'hoursTarget' : number,
  'pendingExpenses' : bigint,
  'hoursThisWeek' : number,
  'remainingVacationMinutes' : bigint,
  'approvedVacationDays' : bigint,
  'pendingVacations' : bigint,
}
export interface Employee {
  'id' : EmployeeId,
  'ort' : [] | [string],
  'plz' : [] | [string],
  'weeklyHoursTarget' : number,
  'active' : boolean,
  'postfach' : [] | [string],
  'land' : [] | [string],
  'role' : Role,
  'email' : string,
  'geburtsdatum' : [] | [bigint],
  'employmentType' : EmploymentType,
  'adresseZusatz1' : [] | [string],
  'adresseZusatz2' : [] | [string],
  'lastName' : string,
  'principalId' : [] | [Principal],
  'strasse' : [] | [string],
  'startDate' : string,
  'companyId' : CompanyId,
  'firstName' : string,
}
export type EmployeeId = bigint;
export interface Employment {
  'id' : string,
  'bis' : [] | [bigint],
  'von' : bigint,
  'pensum' : number,
  'feiertagsberechnungsart' : FeiertagsberechnungsartType,
  'stundenDi' : bigint,
  'stundenDo' : bigint,
  'stundenFr' : bigint,
  'stundenMi' : bigint,
  'stundenMo' : bigint,
  'stundenSa' : bigint,
  'stundenSo' : bigint,
  'employeeId' : EmployeeId,
  'funktion' : string,
  'companyId' : CompanyId,
}
export type EmploymentType = { 'partTime' : null } |
  { 'fullTime' : null } |
  { 'contractor' : null };
export type Erfassungsart = { 'zeitBlock' : null } |
  { 'dauer' : null };
export interface Expense {
  'id' : ExpenseId,
  'status' : ExpenseStatus,
  'date' : string,
  'description' : string,
  'employeeId' : EmployeeId,
  'resetReason' : [] | [string],
  'billableCHF' : number,
  'reimbursementCHF' : number,
  'expenseTypeId' : ExpenseTypeId,
  'receiptBlobId' : [] | [string],
  'companyId' : CompanyId,
}
export interface ExpenseFilter {
  'status' : [] | [ExpenseStatus],
  'dateTo' : [] | [string],
  'employeeId' : [] | [EmployeeId],
  'dateFrom' : [] | [string],
}
export type ExpenseId = bigint;
export type ExpenseStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ExpenseType {
  'id' : ExpenseTypeId,
  'aktiv' : boolean,
  'name' : string,
  'billable' : boolean,
  'reimbursable' : boolean,
  'companyId' : CompanyId,
}
export type ExpenseTypeId = bigint;
export type FeiertagsberechnungsartType = { 'exaktWochentag' : null } |
  { 'entschaedigt' : null } |
  { 'exakt' : null } |
  { 'prozentual' : null };
export interface Holiday {
  'id' : HolidayId,
  'ganztaegig' : boolean,
  'date' : string,
  'name' : string,
  'companyId' : CompanyId,
}
export type HolidayId = bigint;
export type KundeZeiterfassungsart = { 'stuendlich' : null } |
  { 'block' : null };
export interface Project {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'erfassungsart' : [] | [Erfassungsart],
  'active' : boolean,
  'code' : string,
  'billableRate' : number,
  'name' : string,
  'customerId' : CustomerId,
  'kurzbezeichnung' : string,
  'projektleiter' : [] | [EmployeeId],
  'companyId' : CompanyId,
}
export interface ProjectAssignment {
  'employeeId' : EmployeeId,
  'projectId' : ProjectId,
  'companyId' : CompanyId,
}
export type ProjectId = bigint;
export interface ProjectMemberAssignment {
  'stundensatz' : number,
  'employeeId' : EmployeeId,
  'serviceTypeId' : ServiceTypeId,
}
export type ProjectStatus = { 'aktiv' : null } |
  { 'inaktiv' : null } |
  { 'abgeschlossen' : null };
export interface Rechnungsadresse {
  'ort' : [] | [string],
  'plz' : [] | [string],
  'zusatz1' : [] | [string],
  'zusatz2' : [] | [string],
  'postfach' : [] | [string],
  'land' : string,
  'strasse' : [] | [string],
}
export interface ReportData {
  'expenses' : number,
  'entries' : Array<TimeEntry>,
  'billableHours' : number,
  'expenseItems' : Array<Expense>,
}
export interface ReportFilter {
  'dateTo' : string,
  'employeeId' : [] | [EmployeeId],
  'projectId' : [] | [ProjectId],
  'customerId' : [] | [CompanyId],
  'dateFrom' : string,
}
export type Result = { 'ok' : VacationBalance } |
  { 'err' : string };
export type Result_1 = { 'ok' : UserNotificationSettings } |
  { 'err' : string };
export type Result_10 = { 'ok' : Employee } |
  { 'err' : string };
export type Result_11 = { 'ok' : Customer } |
  { 'err' : string };
export type Result_12 = { 'ok' : CompanySettings } |
  { 'err' : string };
export type Result_13 = { 'ok' : Company } |
  { 'err' : string };
export type Result_14 = { 'ok' : AbsenceType } |
  { 'err' : string };
export type Result_15 = { 'ok' : Absence } |
  { 'err' : string };
export type Result_16 = { 'ok' : null } |
  { 'err' : string };
export type Result_17 = { 'ok' : Array<VacationBalance> } |
  { 'err' : string };
export type Result_18 = { 'ok' : Array<TimeBalanceCorrection> } |
  { 'err' : string };
export type Result_19 = { 'ok' : Array<Employment> } |
  { 'err' : string };
export type Result_2 = { 'ok' : TimeEntry } |
  { 'err' : string };
export type Result_20 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_21 = { 'ok' : Standardarbeitszeiten } |
  { 'err' : string };
export type Result_22 = { 'ok' : Array<ProjectMemberAssignment> } |
  { 'err' : string };
export type Result_23 = { 'ok' : [] | [Employment] } |
  { 'err' : string };
export type Result_24 = { 'ok' : WorkTimeBalance } |
  { 'err' : string };
export type Result_25 = { 'ok' : string } |
  { 'err' : string };
export type Result_26 = { 'ok' : ProjectAssignment } |
  { 'err' : string };
export type Result_3 = { 'ok' : TimeBalanceCorrection } |
  { 'err' : string };
export type Result_4 = { 'ok' : ServiceType } |
  { 'err' : string };
export type Result_5 = { 'ok' : Project } |
  { 'err' : string };
export type Result_6 = { 'ok' : Holiday } |
  { 'err' : string };
export type Result_7 = { 'ok' : ExpenseType } |
  { 'err' : string };
export type Result_8 = { 'ok' : Expense } |
  { 'err' : string };
export type Result_9 = { 'ok' : Employment } |
  { 'err' : string };
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'employee' : null };
export interface ServiceType {
  'id' : ServiceTypeId,
  'defaultRate' : number,
  'aktiv' : boolean,
  'name' : string,
  'billable' : boolean,
  'companyId' : CompanyId,
}
export type ServiceTypeId = bigint;
export interface StandardTimeBlock { 'bis' : string, 'von' : string }
export interface Standardarbeitszeiten {
  'tuesday' : Array<StandardTimeBlock>,
  'wednesday' : Array<StandardTimeBlock>,
  'saturday' : Array<StandardTimeBlock>,
  'thursday' : Array<StandardTimeBlock>,
  'sunday' : Array<StandardTimeBlock>,
  'friday' : Array<StandardTimeBlock>,
  'monday' : Array<StandardTimeBlock>,
}
export type Time = bigint;
export interface TimeBalanceCorrection {
  'id' : string,
  'typ' : { 'gutschrift' : null } |
    { 'reduktion' : null },
  'ueberzeit' : bigint,
  'bemerkung' : string,
  'employeeId' : EmployeeId,
  'wirkungsdatum' : bigint,
  'dauer' : bigint,
  'companyId' : CompanyId,
}
export interface TimeEntry {
  'id' : TimeEntryId,
  'bis' : [] | [string],
  'von' : [] | [string],
  'hours' : number,
  'date' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'employeeId' : EmployeeId,
  'billable' : boolean,
  'projectId' : ProjectId,
  'serviceTypeId' : ServiceTypeId,
  'companyId' : CompanyId,
}
export interface TimeEntryFilter {
  'dateTo' : [] | [string],
  'employeeId' : [] | [EmployeeId],
  'projectId' : [] | [ProjectId],
  'dateFrom' : [] | [string],
}
export type TimeEntryId = bigint;
export type Timestamp = bigint;
export interface UpdateAbsenceInput {
  'dateTo' : [] | [string],
  'ganztaetig' : [] | [boolean],
  'description' : [] | [string],
  'dateFrom' : [] | [string],
  'dauer' : [] | [bigint],
}
export interface UpdateAbsenceTypeInput {
  'aktiv' : [] | [boolean],
  'name' : [] | [string],
  'requiresApproval' : [] | [boolean],
  'compensated' : [] | [boolean],
}
export interface UpdateCompanyInput {
  'taxId' : [] | [string],
  'name' : [] | [string],
  'logoUrl' : [] | [string],
  'address' : [] | [string],
}
export interface UpdateCustomerInput {
  'rechnungsadresse' : [] | [Rechnungsadresse],
  'contact' : [] | [string],
  'aktiv' : [] | [boolean],
  'name' : [] | [string],
  'zeiterfassungsart' : [] | [KundeZeiterfassungsart],
  'kundennummer' : [] | [string],
  'notes' : [] | [string],
  'beschreibung' : [] | [string],
  'waehrung' : [] | [string],
}
export interface UpdateEmployeeInput {
  'ort' : [] | [string],
  'plz' : [] | [string],
  'weeklyHoursTarget' : [] | [number],
  'active' : [] | [boolean],
  'postfach' : [] | [string],
  'land' : [] | [string],
  'role' : [] | [Role],
  'email' : [] | [string],
  'geburtsdatum' : [] | [bigint],
  'employmentType' : [] | [EmploymentType],
  'adresseZusatz1' : [] | [string],
  'adresseZusatz2' : [] | [string],
  'lastName' : [] | [string],
  'strasse' : [] | [string],
  'startDate' : [] | [string],
  'firstName' : [] | [string],
}
export interface UpdateEmploymentInput {
  'bis' : [] | [bigint],
  'von' : [] | [bigint],
  'pensum' : number,
  'feiertagsberechnungsart' : [] | [FeiertagsberechnungsartType],
  'stundenDi' : bigint,
  'stundenDo' : bigint,
  'stundenFr' : bigint,
  'stundenMi' : bigint,
  'stundenMo' : bigint,
  'stundenSa' : bigint,
  'stundenSo' : bigint,
  'funktion' : [] | [string],
}
export interface UpdateExpenseInput {
  'date' : [] | [string],
  'description' : [] | [string],
  'billableCHF' : [] | [number],
  'reimbursementCHF' : [] | [number],
  'expenseTypeId' : [] | [ExpenseTypeId],
  'receiptBlobId' : [] | [string],
}
export interface UpdateExpenseTypeInput {
  'aktiv' : [] | [boolean],
  'name' : [] | [string],
  'billable' : [] | [boolean],
  'reimbursable' : [] | [boolean],
}
export interface UpdateHolidayInput {
  'ganztaegig' : [] | [boolean],
  'date' : [] | [string],
  'name' : [] | [string],
}
export interface UpdateProjectInput {
  'status' : [] | [ProjectStatus],
  'erfassungsart' : [] | [Erfassungsart],
  'active' : [] | [boolean],
  'code' : [] | [string],
  'billableRate' : [] | [number],
  'name' : [] | [string],
  'customerId' : [] | [CustomerId],
  'kurzbezeichnung' : [] | [string],
  'projektleiter' : [] | [EmployeeId],
}
export interface UpdateServiceTypeInput {
  'defaultRate' : [] | [number],
  'aktiv' : [] | [boolean],
  'name' : [] | [string],
  'billable' : [] | [boolean],
}
export interface UpdateTimeBalanceCorrectionInput {
  'typ' : [] | [{ 'gutschrift' : null } | { 'reduktion' : null }],
  'ueberzeit' : [] | [bigint],
  'bemerkung' : [] | [string],
  'wirkungsdatum' : [] | [bigint],
  'dauer' : [] | [bigint],
}
export interface UpdateTimeEntryInput {
  'bis' : [] | [string],
  'von' : [] | [string],
  'hours' : [] | [number],
  'date' : [] | [string],
  'description' : [] | [string],
  'billable' : [] | [boolean],
  'projectId' : [] | [ProjectId],
  'serviceTypeId' : [] | [ServiceTypeId],
}
export interface UpdateVacationBalanceInput {
  'verfallsdatum' : [] | [bigint],
  'kalenderjahr' : [] | [bigint],
  'dauer' : [] | [bigint],
}
export interface UserNotificationSettings {
  'emailNewVacationRequest' : boolean,
  'emailOnApproval' : boolean,
  'principalId' : Principal,
  'companyId' : CompanyId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VacationBalance {
  'id' : string,
  'verfallsdatum' : [] | [bigint],
  'employeeId' : EmployeeId,
  'kalenderjahr' : bigint,
  'dauer' : bigint,
  'companyId' : CompanyId,
}
export interface WorkTimeBalance {
  'istStunden' : bigint,
  'ueberzeit' : bigint,
  'saldo' : bigint,
  'periodEnd' : string,
  'periodStart' : string,
  'sollStunden' : bigint,
  'korrektionen' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveAbsence' : ActorMethod<[AbsenceId], Result_15>,
  'approveExpense' : ActorMethod<[ExpenseId], Result_8>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignEmployeeToProject' : ActorMethod<[EmployeeId, ProjectId], Result_26>,
  'createAbsence' : ActorMethod<[CreateAbsenceInput], Result_15>,
  'createAbsenceType' : ActorMethod<[CreateAbsenceTypeInput], Result_14>,
  'createCustomer' : ActorMethod<[CreateCustomerInput], Result_11>,
  'createEmployee' : ActorMethod<[CreateEmployeeInput], Result_10>,
  'createEmployment' : ActorMethod<
    [EmployeeId, CreateEmploymentInput],
    Result_9
  >,
  'createExpense' : ActorMethod<[CreateExpenseInput], Result_8>,
  'createExpenseType' : ActorMethod<[CreateExpenseTypeInput], Result_7>,
  'createHoliday' : ActorMethod<[CreateHolidayInput], Result_6>,
  'createProject' : ActorMethod<[CreateProjectInput], Result_5>,
  'createServiceType' : ActorMethod<[CreateServiceTypeInput], Result_4>,
  'createTimeBalanceCorrection' : ActorMethod<
    [EmployeeId, CreateTimeBalanceCorrectionInput],
    Result_3
  >,
  'createTimeEntry' : ActorMethod<[CreateTimeEntryInput], Result_2>,
  'createVacationBalance' : ActorMethod<
    [EmployeeId, CreateVacationBalanceInput],
    Result
  >,
  'deleteAbsence' : ActorMethod<[AbsenceId], Result_16>,
  'deleteAbsenceType' : ActorMethod<[AbsenceTypeId], Result_16>,
  'deleteCustomer' : ActorMethod<[CustomerId], Result_16>,
  'deleteEmployee' : ActorMethod<[EmployeeId], Result_16>,
  'deleteEmployment' : ActorMethod<[EmployeeId, string], Result_16>,
  'deleteExpense' : ActorMethod<[ExpenseId], Result_16>,
  'deleteExpenseType' : ActorMethod<[ExpenseTypeId], Result_16>,
  'deleteHoliday' : ActorMethod<[HolidayId], Result_16>,
  'deleteProject' : ActorMethod<[ProjectId], Result_16>,
  'deleteServiceType' : ActorMethod<[ServiceTypeId], Result_16>,
  'deleteTimeBalanceCorrection' : ActorMethod<[EmployeeId, string], Result_16>,
  'deleteTimeEntry' : ActorMethod<[TimeEntryId], Result_16>,
  'deleteVacationBalance' : ActorMethod<[EmployeeId, string], Result_16>,
  'generateInviteCode' : ActorMethod<[EmployeeId], Result_25>,
  'getCalendarEntries' : ActorMethod<[string, bigint], CalendarData>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanySettings' : ActorMethod<[], Result_12>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEmployeeWorkTimeBalance' : ActorMethod<
    [EmployeeId, string, string],
    Result_24
  >,
  'getEmployeeWorkTimeBalanceFromStart' : ActorMethod<[EmployeeId], Result_24>,
  'getEmploymentForDate' : ActorMethod<[EmployeeId, string], Result_23>,
  'getMyCompany' : ActorMethod<[], Result_13>,
  'getMyEmployee' : ActorMethod<[], Result_10>,
  'getMyStandardarbeitszeiten' : ActorMethod<[], Result_21>,
  'getProjectMembers' : ActorMethod<[ProjectId], Result_22>,
  'getReportData' : ActorMethod<[ReportFilter], ReportData>,
  'getStandardarbeitszeitenForEmployee' : ActorMethod<[EmployeeId], Result_21>,
  'getTimeBalance' : ActorMethod<[EmployeeId], Result_20>,
  'getUserNotificationSettings' : ActorMethod<[], Result_1>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'listAbsenceTypes' : ActorMethod<[], Array<AbsenceType>>,
  'listAbsences' : ActorMethod<[AbsenceFilter], Array<Absence>>,
  'listAuditLog' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<AuditEntry>
  >,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listEmployees' : ActorMethod<[], Array<Employee>>,
  'listEmployments' : ActorMethod<[EmployeeId], Result_19>,
  'listExpenseTypes' : ActorMethod<[], Array<ExpenseType>>,
  'listExpenses' : ActorMethod<[ExpenseFilter], Array<Expense>>,
  'listHolidays' : ActorMethod<[], Array<Holiday>>,
  'listProjectAssignments' : ActorMethod<[], Array<ProjectAssignment>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listServiceTypes' : ActorMethod<[], Array<ServiceType>>,
  'listTimeBalanceCorrections' : ActorMethod<[EmployeeId], Result_18>,
  'listTimeEntries' : ActorMethod<[TimeEntryFilter], Array<TimeEntry>>,
  'listVacationBalances' : ActorMethod<[EmployeeId], Result_17>,
  'redeemInviteCode' : ActorMethod<[string], Result_10>,
  'registerCompany' : ActorMethod<[string, string, string, string], Result_13>,
  'rejectAbsence' : ActorMethod<[AbsenceId, string], Result_15>,
  'rejectExpense' : ActorMethod<[ExpenseId, [] | [string]], Result_8>,
  'removeEmployeeFromProject' : ActorMethod<[EmployeeId, ProjectId], Result_16>,
  'resetAbsenceToAusstehend' : ActorMethod<[AbsenceId, string], Result_15>,
  'resetExpenseToAusstehend' : ActorMethod<[ExpenseId, string], Result_8>,
  'revokeInviteCode' : ActorMethod<[string], Result_16>,
  'setMyStandardarbeitszeiten' : ActorMethod<
    [Standardarbeitszeiten],
    Result_16
  >,
  'setProjectMembers' : ActorMethod<
    [ProjectId, Array<ProjectMemberAssignment>],
    Result_16
  >,
  'setStandardarbeitszeitenForEmployee' : ActorMethod<
    [EmployeeId, Standardarbeitszeiten],
    Result_16
  >,
  'updateAbsence' : ActorMethod<[AbsenceId, UpdateAbsenceInput], Result_15>,
  'updateAbsenceType' : ActorMethod<
    [AbsenceTypeId, UpdateAbsenceTypeInput],
    Result_14
  >,
  'updateCompany' : ActorMethod<[UpdateCompanyInput], Result_13>,
  'updateCompanySettings' : ActorMethod<[CompanySettings], Result_12>,
  'updateCustomer' : ActorMethod<[CustomerId, UpdateCustomerInput], Result_11>,
  'updateEmployee' : ActorMethod<[EmployeeId, UpdateEmployeeInput], Result_10>,
  'updateEmployment' : ActorMethod<
    [EmployeeId, string, UpdateEmploymentInput],
    Result_9
  >,
  'updateExpense' : ActorMethod<[ExpenseId, UpdateExpenseInput], Result_8>,
  'updateExpenseType' : ActorMethod<
    [ExpenseTypeId, UpdateExpenseTypeInput],
    Result_7
  >,
  'updateHoliday' : ActorMethod<[HolidayId, UpdateHolidayInput], Result_6>,
  'updateProject' : ActorMethod<[ProjectId, UpdateProjectInput], Result_5>,
  'updateServiceType' : ActorMethod<
    [ServiceTypeId, UpdateServiceTypeInput],
    Result_4
  >,
  'updateTimeBalanceCorrection' : ActorMethod<
    [EmployeeId, string, UpdateTimeBalanceCorrectionInput],
    Result_3
  >,
  'updateTimeEntry' : ActorMethod<
    [TimeEntryId, UpdateTimeEntryInput],
    Result_2
  >,
  'updateUserNotificationSettings' : ActorMethod<
    [UserNotificationSettings],
    Result_1
  >,
  'updateVacationBalance' : ActorMethod<
    [EmployeeId, string, UpdateVacationBalanceInput],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];