/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AbsenceId = IDL.Nat;
export const AbsenceStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AbsenceTypeId = IDL.Nat;
export const Timestamp = IDL.Int;
export const EmployeeId = IDL.Nat;
export const CompanyId = IDL.Nat;
export const Absence = IDL.Record({
  'id' : AbsenceId,
  'status' : AbsenceStatus,
  'absenceTypeId' : AbsenceTypeId,
  'dateTo' : IDL.Text,
  'ganztaetig' : IDL.Bool,
  'approvedBy' : IDL.Opt(IDL.Principal),
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'employeeId' : EmployeeId,
  'resetReason' : IDL.Opt(IDL.Text),
  'rejectionComment' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Text,
  'dauer' : IDL.Nat,
  'companyId' : CompanyId,
});
export const Result_15 = IDL.Variant({ 'ok' : Absence, 'err' : IDL.Text });
export const ExpenseId = IDL.Nat;
export const ExpenseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExpenseTypeId = IDL.Nat;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'status' : ExpenseStatus,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
  'resetReason' : IDL.Opt(IDL.Text),
  'billableCHF' : IDL.Float64,
  'reimbursementCHF' : IDL.Float64,
  'expenseTypeId' : ExpenseTypeId,
  'receiptBlobId' : IDL.Opt(IDL.Text),
  'companyId' : CompanyId,
});
export const Result_8 = IDL.Variant({ 'ok' : Expense, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectId = IDL.Nat;
export const ProjectAssignment = IDL.Record({
  'employeeId' : EmployeeId,
  'projectId' : ProjectId,
  'companyId' : CompanyId,
});
export const Result_26 = IDL.Variant({
  'ok' : ProjectAssignment,
  'err' : IDL.Text,
});
export const CreateAbsenceInput = IDL.Record({
  'absenceTypeId' : AbsenceTypeId,
  'dateTo' : IDL.Text,
  'ganztaetig' : IDL.Bool,
  'description' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Text,
  'dauer' : IDL.Nat,
});
export const CreateAbsenceTypeInput = IDL.Record({
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Text,
  'requiresApproval' : IDL.Bool,
  'compensated' : IDL.Bool,
});
export const AbsenceType = IDL.Record({
  'id' : AbsenceTypeId,
  'aktiv' : IDL.Bool,
  'name' : IDL.Text,
  'requiresApproval' : IDL.Bool,
  'compensated' : IDL.Bool,
  'companyId' : CompanyId,
});
export const Result_14 = IDL.Variant({ 'ok' : AbsenceType, 'err' : IDL.Text });
export const Rechnungsadresse = IDL.Record({
  'ort' : IDL.Opt(IDL.Text),
  'plz' : IDL.Opt(IDL.Text),
  'zusatz1' : IDL.Opt(IDL.Text),
  'zusatz2' : IDL.Opt(IDL.Text),
  'postfach' : IDL.Opt(IDL.Text),
  'land' : IDL.Text,
  'strasse' : IDL.Opt(IDL.Text),
});
export const KundeZeiterfassungsart = IDL.Variant({
  'stuendlich' : IDL.Null,
  'block' : IDL.Null,
});
export const CreateCustomerInput = IDL.Record({
  'rechnungsadresse' : IDL.Opt(Rechnungsadresse),
  'contact' : IDL.Opt(IDL.Text),
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Text,
  'zeiterfassungsart' : IDL.Opt(KundeZeiterfassungsart),
  'kundennummer' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'beschreibung' : IDL.Opt(IDL.Text),
  'waehrung' : IDL.Opt(IDL.Text),
});
export const CustomerId = IDL.Nat;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'rechnungsadresse' : IDL.Opt(Rechnungsadresse),
  'contact' : IDL.Opt(IDL.Text),
  'aktiv' : IDL.Bool,
  'name' : IDL.Text,
  'zeiterfassungsart' : KundeZeiterfassungsart,
  'kundennummer' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'beschreibung' : IDL.Opt(IDL.Text),
  'waehrung' : IDL.Text,
  'companyId' : CompanyId,
});
export const Result_11 = IDL.Variant({ 'ok' : Customer, 'err' : IDL.Text });
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'employee' : IDL.Null,
});
export const EmploymentType = IDL.Variant({
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
  'contractor' : IDL.Null,
});
export const CreateEmployeeInput = IDL.Record({
  'ort' : IDL.Opt(IDL.Text),
  'plz' : IDL.Opt(IDL.Text),
  'weeklyHoursTarget' : IDL.Float64,
  'postfach' : IDL.Opt(IDL.Text),
  'land' : IDL.Opt(IDL.Text),
  'role' : Role,
  'email' : IDL.Text,
  'geburtsdatum' : IDL.Opt(IDL.Int),
  'employmentType' : EmploymentType,
  'adresseZusatz1' : IDL.Opt(IDL.Text),
  'adresseZusatz2' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Text,
  'strasse' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'ort' : IDL.Opt(IDL.Text),
  'plz' : IDL.Opt(IDL.Text),
  'weeklyHoursTarget' : IDL.Float64,
  'active' : IDL.Bool,
  'postfach' : IDL.Opt(IDL.Text),
  'land' : IDL.Opt(IDL.Text),
  'role' : Role,
  'email' : IDL.Text,
  'geburtsdatum' : IDL.Opt(IDL.Int),
  'employmentType' : EmploymentType,
  'adresseZusatz1' : IDL.Opt(IDL.Text),
  'adresseZusatz2' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Text,
  'principalId' : IDL.Opt(IDL.Principal),
  'strasse' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Text,
  'companyId' : CompanyId,
  'firstName' : IDL.Text,
});
export const Result_10 = IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text });
export const FeiertagsberechnungsartType = IDL.Variant({
  'exaktWochentag' : IDL.Null,
  'entschaedigt' : IDL.Null,
  'exakt' : IDL.Null,
  'prozentual' : IDL.Null,
});
export const CreateEmploymentInput = IDL.Record({
  'bis' : IDL.Opt(IDL.Int),
  'von' : IDL.Int,
  'pensum' : IDL.Float64,
  'feiertagsberechnungsart' : FeiertagsberechnungsartType,
  'stundenDi' : IDL.Nat,
  'stundenDo' : IDL.Nat,
  'stundenFr' : IDL.Nat,
  'stundenMi' : IDL.Nat,
  'stundenMo' : IDL.Nat,
  'stundenSa' : IDL.Nat,
  'stundenSo' : IDL.Nat,
  'funktion' : IDL.Text,
});
export const Employment = IDL.Record({
  'id' : IDL.Text,
  'bis' : IDL.Opt(IDL.Int),
  'von' : IDL.Int,
  'pensum' : IDL.Float64,
  'feiertagsberechnungsart' : FeiertagsberechnungsartType,
  'stundenDi' : IDL.Nat,
  'stundenDo' : IDL.Nat,
  'stundenFr' : IDL.Nat,
  'stundenMi' : IDL.Nat,
  'stundenMo' : IDL.Nat,
  'stundenSa' : IDL.Nat,
  'stundenSo' : IDL.Nat,
  'employeeId' : EmployeeId,
  'funktion' : IDL.Text,
  'companyId' : CompanyId,
});
export const Result_9 = IDL.Variant({ 'ok' : Employment, 'err' : IDL.Text });
export const CreateExpenseInput = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'billableCHF' : IDL.Float64,
  'reimbursementCHF' : IDL.Float64,
  'expenseTypeId' : ExpenseTypeId,
  'receiptBlobId' : IDL.Opt(IDL.Text),
});
export const CreateExpenseTypeInput = IDL.Record({
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Text,
  'billable' : IDL.Bool,
  'reimbursable' : IDL.Bool,
});
export const ExpenseType = IDL.Record({
  'id' : ExpenseTypeId,
  'aktiv' : IDL.Bool,
  'name' : IDL.Text,
  'billable' : IDL.Bool,
  'reimbursable' : IDL.Bool,
  'companyId' : CompanyId,
});
export const Result_7 = IDL.Variant({ 'ok' : ExpenseType, 'err' : IDL.Text });
export const CreateHolidayInput = IDL.Record({
  'ganztaegig' : IDL.Opt(IDL.Bool),
  'date' : IDL.Text,
  'name' : IDL.Text,
});
export const HolidayId = IDL.Nat;
export const Holiday = IDL.Record({
  'id' : HolidayId,
  'ganztaegig' : IDL.Bool,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'companyId' : CompanyId,
});
export const Result_6 = IDL.Variant({ 'ok' : Holiday, 'err' : IDL.Text });
export const ProjectStatus = IDL.Variant({
  'aktiv' : IDL.Null,
  'inaktiv' : IDL.Null,
  'abgeschlossen' : IDL.Null,
});
export const Erfassungsart = IDL.Variant({
  'zeitBlock' : IDL.Null,
  'dauer' : IDL.Null,
});
export const CreateProjectInput = IDL.Record({
  'status' : IDL.Opt(ProjectStatus),
  'erfassungsart' : IDL.Opt(Erfassungsart),
  'code' : IDL.Text,
  'billableRate' : IDL.Float64,
  'name' : IDL.Text,
  'customerId' : CustomerId,
  'kurzbezeichnung' : IDL.Text,
  'projektleiter' : IDL.Opt(EmployeeId),
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'erfassungsart' : IDL.Opt(Erfassungsart),
  'active' : IDL.Bool,
  'code' : IDL.Text,
  'billableRate' : IDL.Float64,
  'name' : IDL.Text,
  'customerId' : CustomerId,
  'kurzbezeichnung' : IDL.Text,
  'projektleiter' : IDL.Opt(EmployeeId),
  'companyId' : CompanyId,
});
export const Result_5 = IDL.Variant({ 'ok' : Project, 'err' : IDL.Text });
export const CreateServiceTypeInput = IDL.Record({
  'defaultRate' : IDL.Float64,
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Text,
  'billable' : IDL.Bool,
});
export const ServiceTypeId = IDL.Nat;
export const ServiceType = IDL.Record({
  'id' : ServiceTypeId,
  'defaultRate' : IDL.Float64,
  'aktiv' : IDL.Bool,
  'name' : IDL.Text,
  'billable' : IDL.Bool,
  'companyId' : CompanyId,
});
export const Result_4 = IDL.Variant({ 'ok' : ServiceType, 'err' : IDL.Text });
export const CreateTimeBalanceCorrectionInput = IDL.Record({
  'typ' : IDL.Variant({ 'gutschrift' : IDL.Null, 'reduktion' : IDL.Null }),
  'ueberzeit' : IDL.Int,
  'bemerkung' : IDL.Text,
  'wirkungsdatum' : IDL.Int,
  'dauer' : IDL.Int,
});
export const TimeBalanceCorrection = IDL.Record({
  'id' : IDL.Text,
  'typ' : IDL.Variant({ 'gutschrift' : IDL.Null, 'reduktion' : IDL.Null }),
  'ueberzeit' : IDL.Int,
  'bemerkung' : IDL.Text,
  'employeeId' : EmployeeId,
  'wirkungsdatum' : IDL.Int,
  'dauer' : IDL.Int,
  'companyId' : CompanyId,
});
export const Result_3 = IDL.Variant({
  'ok' : TimeBalanceCorrection,
  'err' : IDL.Text,
});
export const CreateTimeEntryInput = IDL.Record({
  'bis' : IDL.Opt(IDL.Text),
  'von' : IDL.Opt(IDL.Text),
  'hours' : IDL.Float64,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'billable' : IDL.Bool,
  'projectId' : ProjectId,
  'serviceTypeId' : ServiceTypeId,
});
export const TimeEntryId = IDL.Nat;
export const TimeEntry = IDL.Record({
  'id' : TimeEntryId,
  'bis' : IDL.Opt(IDL.Text),
  'von' : IDL.Opt(IDL.Text),
  'hours' : IDL.Float64,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
  'billable' : IDL.Bool,
  'projectId' : ProjectId,
  'serviceTypeId' : ServiceTypeId,
  'companyId' : CompanyId,
});
export const Result_2 = IDL.Variant({ 'ok' : TimeEntry, 'err' : IDL.Text });
export const CreateVacationBalanceInput = IDL.Record({
  'verfallsdatum' : IDL.Opt(IDL.Int),
  'kalenderjahr' : IDL.Int,
  'dauer' : IDL.Int,
});
export const VacationBalance = IDL.Record({
  'id' : IDL.Text,
  'verfallsdatum' : IDL.Opt(IDL.Int),
  'employeeId' : EmployeeId,
  'kalenderjahr' : IDL.Int,
  'dauer' : IDL.Int,
  'companyId' : CompanyId,
});
export const Result = IDL.Variant({ 'ok' : VacationBalance, 'err' : IDL.Text });
export const Result_16 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_25 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const CalendarData = IDL.Record({
  'absences' : IDL.Vec(Absence),
  'expenses' : IDL.Vec(Expense),
  'timeEntries' : IDL.Vec(TimeEntry),
});
export const CompanySettings = IDL.Record({
  'timezone' : IDL.Text,
  'approvalRequired' : IDL.Bool,
  'allowExpiredVacationBalance' : IDL.Bool,
  'emailNewVacationRequest' : IDL.Bool,
  'emailOnApproval' : IDL.Bool,
  'vacationCarryoverDays' : IDL.Nat,
  'maxVacationDays' : IDL.Nat,
  'companyId' : CompanyId,
});
export const Result_12 = IDL.Variant({
  'ok' : CompanySettings,
  'err' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'hoursTarget' : IDL.Float64,
  'pendingExpenses' : IDL.Nat,
  'hoursThisWeek' : IDL.Float64,
  'remainingVacationMinutes' : IDL.Int,
  'approvedVacationDays' : IDL.Nat,
  'pendingVacations' : IDL.Nat,
});
export const WorkTimeBalance = IDL.Record({
  'istStunden' : IDL.Int,
  'ueberzeit' : IDL.Int,
  'saldo' : IDL.Int,
  'periodEnd' : IDL.Text,
  'periodStart' : IDL.Text,
  'sollStunden' : IDL.Int,
  'korrektionen' : IDL.Int,
});
export const Result_24 = IDL.Variant({
  'ok' : WorkTimeBalance,
  'err' : IDL.Text,
});
export const Result_23 = IDL.Variant({
  'ok' : IDL.Opt(Employment),
  'err' : IDL.Text,
});
export const Company = IDL.Record({
  'id' : CompanyId,
  'taxId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'logoUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
});
export const Result_13 = IDL.Variant({ 'ok' : Company, 'err' : IDL.Text });
export const StandardTimeBlock = IDL.Record({
  'bis' : IDL.Text,
  'von' : IDL.Text,
});
export const Standardarbeitszeiten = IDL.Record({
  'tuesday' : IDL.Vec(StandardTimeBlock),
  'wednesday' : IDL.Vec(StandardTimeBlock),
  'saturday' : IDL.Vec(StandardTimeBlock),
  'thursday' : IDL.Vec(StandardTimeBlock),
  'sunday' : IDL.Vec(StandardTimeBlock),
  'friday' : IDL.Vec(StandardTimeBlock),
  'monday' : IDL.Vec(StandardTimeBlock),
});
export const Result_21 = IDL.Variant({
  'ok' : Standardarbeitszeiten,
  'err' : IDL.Text,
});
export const ProjectMemberAssignment = IDL.Record({
  'stundensatz' : IDL.Float64,
  'employeeId' : EmployeeId,
  'serviceTypeId' : ServiceTypeId,
});
export const Result_22 = IDL.Variant({
  'ok' : IDL.Vec(ProjectMemberAssignment),
  'err' : IDL.Text,
});
export const ReportFilter = IDL.Record({
  'dateTo' : IDL.Text,
  'employeeId' : IDL.Opt(EmployeeId),
  'projectId' : IDL.Opt(ProjectId),
  'customerId' : IDL.Opt(CompanyId),
  'dateFrom' : IDL.Text,
});
export const ReportData = IDL.Record({
  'expenses' : IDL.Float64,
  'entries' : IDL.Vec(TimeEntry),
  'billableHours' : IDL.Float64,
  'expenseItems' : IDL.Vec(Expense),
});
export const Result_20 = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
export const UserNotificationSettings = IDL.Record({
  'emailNewVacationRequest' : IDL.Bool,
  'emailOnApproval' : IDL.Bool,
  'principalId' : IDL.Principal,
  'companyId' : CompanyId,
});
export const Result_1 = IDL.Variant({
  'ok' : UserNotificationSettings,
  'err' : IDL.Text,
});
export const AbsenceFilter = IDL.Record({
  'status' : IDL.Opt(AbsenceStatus),
  'absenceTypeId' : IDL.Opt(AbsenceTypeId),
  'dateTo' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Opt(EmployeeId),
  'dateFrom' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'oldStatus' : IDL.Text,
  'action' : IDL.Text,
  'changedBy' : IDL.Principal,
  'timestamp' : Time,
  'targetType' : IDL.Text,
  'newStatus' : IDL.Text,
  'targetId' : IDL.Nat,
  'previousApprovedBy' : IDL.Opt(IDL.Principal),
  'reason' : IDL.Opt(IDL.Text),
});
export const Result_19 = IDL.Variant({
  'ok' : IDL.Vec(Employment),
  'err' : IDL.Text,
});
export const ExpenseFilter = IDL.Record({
  'status' : IDL.Opt(ExpenseStatus),
  'dateTo' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Opt(EmployeeId),
  'dateFrom' : IDL.Opt(IDL.Text),
});
export const Result_18 = IDL.Variant({
  'ok' : IDL.Vec(TimeBalanceCorrection),
  'err' : IDL.Text,
});
export const TimeEntryFilter = IDL.Record({
  'dateTo' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Opt(EmployeeId),
  'projectId' : IDL.Opt(ProjectId),
  'dateFrom' : IDL.Opt(IDL.Text),
});
export const Result_17 = IDL.Variant({
  'ok' : IDL.Vec(VacationBalance),
  'err' : IDL.Text,
});
export const UpdateAbsenceInput = IDL.Record({
  'dateTo' : IDL.Opt(IDL.Text),
  'ganztaetig' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Opt(IDL.Text),
  'dauer' : IDL.Opt(IDL.Nat),
});
export const UpdateAbsenceTypeInput = IDL.Record({
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'requiresApproval' : IDL.Opt(IDL.Bool),
  'compensated' : IDL.Opt(IDL.Bool),
});
export const UpdateCompanyInput = IDL.Record({
  'taxId' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'logoUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
});
export const UpdateCustomerInput = IDL.Record({
  'rechnungsadresse' : IDL.Opt(Rechnungsadresse),
  'contact' : IDL.Opt(IDL.Text),
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'zeiterfassungsart' : IDL.Opt(KundeZeiterfassungsart),
  'kundennummer' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'beschreibung' : IDL.Opt(IDL.Text),
  'waehrung' : IDL.Opt(IDL.Text),
});
export const UpdateEmployeeInput = IDL.Record({
  'ort' : IDL.Opt(IDL.Text),
  'plz' : IDL.Opt(IDL.Text),
  'weeklyHoursTarget' : IDL.Opt(IDL.Float64),
  'active' : IDL.Opt(IDL.Bool),
  'postfach' : IDL.Opt(IDL.Text),
  'land' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(Role),
  'email' : IDL.Opt(IDL.Text),
  'geburtsdatum' : IDL.Opt(IDL.Int),
  'employmentType' : IDL.Opt(EmploymentType),
  'adresseZusatz1' : IDL.Opt(IDL.Text),
  'adresseZusatz2' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Opt(IDL.Text),
  'strasse' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Opt(IDL.Text),
});
export const UpdateEmploymentInput = IDL.Record({
  'bis' : IDL.Opt(IDL.Int),
  'von' : IDL.Opt(IDL.Int),
  'pensum' : IDL.Float64,
  'feiertagsberechnungsart' : IDL.Opt(FeiertagsberechnungsartType),
  'stundenDi' : IDL.Nat,
  'stundenDo' : IDL.Nat,
  'stundenFr' : IDL.Nat,
  'stundenMi' : IDL.Nat,
  'stundenMo' : IDL.Nat,
  'stundenSa' : IDL.Nat,
  'stundenSo' : IDL.Nat,
  'funktion' : IDL.Opt(IDL.Text),
});
export const UpdateExpenseInput = IDL.Record({
  'date' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'billableCHF' : IDL.Opt(IDL.Float64),
  'reimbursementCHF' : IDL.Opt(IDL.Float64),
  'expenseTypeId' : IDL.Opt(ExpenseTypeId),
  'receiptBlobId' : IDL.Opt(IDL.Text),
});
export const UpdateExpenseTypeInput = IDL.Record({
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'billable' : IDL.Opt(IDL.Bool),
  'reimbursable' : IDL.Opt(IDL.Bool),
});
export const UpdateHolidayInput = IDL.Record({
  'ganztaegig' : IDL.Opt(IDL.Bool),
  'date' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
});
export const UpdateProjectInput = IDL.Record({
  'status' : IDL.Opt(ProjectStatus),
  'erfassungsart' : IDL.Opt(Erfassungsart),
  'active' : IDL.Opt(IDL.Bool),
  'code' : IDL.Opt(IDL.Text),
  'billableRate' : IDL.Opt(IDL.Float64),
  'name' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Opt(CustomerId),
  'kurzbezeichnung' : IDL.Opt(IDL.Text),
  'projektleiter' : IDL.Opt(EmployeeId),
});
export const UpdateServiceTypeInput = IDL.Record({
  'defaultRate' : IDL.Opt(IDL.Float64),
  'aktiv' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'billable' : IDL.Opt(IDL.Bool),
});
export const UpdateTimeBalanceCorrectionInput = IDL.Record({
  'typ' : IDL.Opt(
    IDL.Variant({ 'gutschrift' : IDL.Null, 'reduktion' : IDL.Null })
  ),
  'ueberzeit' : IDL.Opt(IDL.Int),
  'bemerkung' : IDL.Opt(IDL.Text),
  'wirkungsdatum' : IDL.Opt(IDL.Int),
  'dauer' : IDL.Opt(IDL.Int),
});
export const UpdateTimeEntryInput = IDL.Record({
  'bis' : IDL.Opt(IDL.Text),
  'von' : IDL.Opt(IDL.Text),
  'hours' : IDL.Opt(IDL.Float64),
  'date' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'billable' : IDL.Opt(IDL.Bool),
  'projectId' : IDL.Opt(ProjectId),
  'serviceTypeId' : IDL.Opt(ServiceTypeId),
});
export const UpdateVacationBalanceInput = IDL.Record({
  'verfallsdatum' : IDL.Opt(IDL.Int),
  'kalenderjahr' : IDL.Opt(IDL.Int),
  'dauer' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveAbsence' : IDL.Func([AbsenceId], [Result_15], []),
  'approveExpense' : IDL.Func([ExpenseId], [Result_8], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignEmployeeToProject' : IDL.Func(
      [EmployeeId, ProjectId],
      [Result_26],
      [],
    ),
  'createAbsence' : IDL.Func([CreateAbsenceInput], [Result_15], []),
  'createAbsenceType' : IDL.Func([CreateAbsenceTypeInput], [Result_14], []),
  'createCustomer' : IDL.Func([CreateCustomerInput], [Result_11], []),
  'createEmployee' : IDL.Func([CreateEmployeeInput], [Result_10], []),
  'createEmployment' : IDL.Func(
      [EmployeeId, CreateEmploymentInput],
      [Result_9],
      [],
    ),
  'createExpense' : IDL.Func([CreateExpenseInput], [Result_8], []),
  'createExpenseType' : IDL.Func([CreateExpenseTypeInput], [Result_7], []),
  'createHoliday' : IDL.Func([CreateHolidayInput], [Result_6], []),
  'createProject' : IDL.Func([CreateProjectInput], [Result_5], []),
  'createServiceType' : IDL.Func([CreateServiceTypeInput], [Result_4], []),
  'createTimeBalanceCorrection' : IDL.Func(
      [EmployeeId, CreateTimeBalanceCorrectionInput],
      [Result_3],
      [],
    ),
  'createTimeEntry' : IDL.Func([CreateTimeEntryInput], [Result_2], []),
  'createVacationBalance' : IDL.Func(
      [EmployeeId, CreateVacationBalanceInput],
      [Result],
      [],
    ),
  'deleteAbsence' : IDL.Func([AbsenceId], [Result_16], []),
  'deleteAbsenceType' : IDL.Func([AbsenceTypeId], [Result_16], []),
  'deleteCustomer' : IDL.Func([CustomerId], [Result_16], []),
  'deleteEmployee' : IDL.Func([EmployeeId], [Result_16], []),
  'deleteEmployment' : IDL.Func([EmployeeId, IDL.Text], [Result_16], []),
  'deleteExpense' : IDL.Func([ExpenseId], [Result_16], []),
  'deleteExpenseType' : IDL.Func([ExpenseTypeId], [Result_16], []),
  'deleteHoliday' : IDL.Func([HolidayId], [Result_16], []),
  'deleteProject' : IDL.Func([ProjectId], [Result_16], []),
  'deleteServiceType' : IDL.Func([ServiceTypeId], [Result_16], []),
  'deleteTimeBalanceCorrection' : IDL.Func(
      [EmployeeId, IDL.Text],
      [Result_16],
      [],
    ),
  'deleteTimeEntry' : IDL.Func([TimeEntryId], [Result_16], []),
  'deleteVacationBalance' : IDL.Func([EmployeeId, IDL.Text], [Result_16], []),
  'generateInviteCode' : IDL.Func([EmployeeId], [Result_25], []),
  'getCalendarEntries' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [CalendarData],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanySettings' : IDL.Func([], [Result_12], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEmployeeWorkTimeBalance' : IDL.Func(
      [EmployeeId, IDL.Text, IDL.Text],
      [Result_24],
      ['query'],
    ),
  'getEmployeeWorkTimeBalanceFromStart' : IDL.Func(
      [EmployeeId],
      [Result_24],
      ['query'],
    ),
  'getEmploymentForDate' : IDL.Func(
      [EmployeeId, IDL.Text],
      [Result_23],
      ['query'],
    ),
  'getMyCompany' : IDL.Func([], [Result_13], ['query']),
  'getMyEmployee' : IDL.Func([], [Result_10], ['query']),
  'getMyStandardarbeitszeiten' : IDL.Func([], [Result_21], ['query']),
  'getProjectMembers' : IDL.Func([ProjectId], [Result_22], ['query']),
  'getReportData' : IDL.Func([ReportFilter], [ReportData], ['query']),
  'getStandardarbeitszeitenForEmployee' : IDL.Func(
      [EmployeeId],
      [Result_21],
      ['query'],
    ),
  'getTimeBalance' : IDL.Func([EmployeeId], [Result_20], ['query']),
  'getUserNotificationSettings' : IDL.Func([], [Result_1], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listAbsenceTypes' : IDL.Func([], [IDL.Vec(AbsenceType)], ['query']),
  'listAbsences' : IDL.Func([AbsenceFilter], [IDL.Vec(Absence)], ['query']),
  'listAuditLog' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listEmployments' : IDL.Func([EmployeeId], [Result_19], ['query']),
  'listExpenseTypes' : IDL.Func([], [IDL.Vec(ExpenseType)], ['query']),
  'listExpenses' : IDL.Func([ExpenseFilter], [IDL.Vec(Expense)], ['query']),
  'listHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'listProjectAssignments' : IDL.Func(
      [],
      [IDL.Vec(ProjectAssignment)],
      ['query'],
    ),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listServiceTypes' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
  'listTimeBalanceCorrections' : IDL.Func([EmployeeId], [Result_18], ['query']),
  'listTimeEntries' : IDL.Func(
      [TimeEntryFilter],
      [IDL.Vec(TimeEntry)],
      ['query'],
    ),
  'listVacationBalances' : IDL.Func([EmployeeId], [Result_17], ['query']),
  'redeemInviteCode' : IDL.Func([IDL.Text], [Result_10], []),
  'registerCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_13],
      [],
    ),
  'rejectAbsence' : IDL.Func([AbsenceId, IDL.Text], [Result_15], []),
  'rejectExpense' : IDL.Func([ExpenseId, IDL.Opt(IDL.Text)], [Result_8], []),
  'removeEmployeeFromProject' : IDL.Func(
      [EmployeeId, ProjectId],
      [Result_16],
      [],
    ),
  'resetAbsenceToAusstehend' : IDL.Func([AbsenceId, IDL.Text], [Result_15], []),
  'resetExpenseToAusstehend' : IDL.Func([ExpenseId, IDL.Text], [Result_8], []),
  'revokeInviteCode' : IDL.Func([IDL.Text], [Result_16], []),
  'setMyStandardarbeitszeiten' : IDL.Func(
      [Standardarbeitszeiten],
      [Result_16],
      [],
    ),
  'setProjectMembers' : IDL.Func(
      [ProjectId, IDL.Vec(ProjectMemberAssignment)],
      [Result_16],
      [],
    ),
  'setStandardarbeitszeitenForEmployee' : IDL.Func(
      [EmployeeId, Standardarbeitszeiten],
      [Result_16],
      [],
    ),
  'updateAbsence' : IDL.Func([AbsenceId, UpdateAbsenceInput], [Result_15], []),
  'updateAbsenceType' : IDL.Func(
      [AbsenceTypeId, UpdateAbsenceTypeInput],
      [Result_14],
      [],
    ),
  'updateCompany' : IDL.Func([UpdateCompanyInput], [Result_13], []),
  'updateCompanySettings' : IDL.Func([CompanySettings], [Result_12], []),
  'updateCustomer' : IDL.Func(
      [CustomerId, UpdateCustomerInput],
      [Result_11],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [EmployeeId, UpdateEmployeeInput],
      [Result_10],
      [],
    ),
  'updateEmployment' : IDL.Func(
      [EmployeeId, IDL.Text, UpdateEmploymentInput],
      [Result_9],
      [],
    ),
  'updateExpense' : IDL.Func([ExpenseId, UpdateExpenseInput], [Result_8], []),
  'updateExpenseType' : IDL.Func(
      [ExpenseTypeId, UpdateExpenseTypeInput],
      [Result_7],
      [],
    ),
  'updateHoliday' : IDL.Func([HolidayId, UpdateHolidayInput], [Result_6], []),
  'updateProject' : IDL.Func([ProjectId, UpdateProjectInput], [Result_5], []),
  'updateServiceType' : IDL.Func(
      [ServiceTypeId, UpdateServiceTypeInput],
      [Result_4],
      [],
    ),
  'updateTimeBalanceCorrection' : IDL.Func(
      [EmployeeId, IDL.Text, UpdateTimeBalanceCorrectionInput],
      [Result_3],
      [],
    ),
  'updateTimeEntry' : IDL.Func(
      [TimeEntryId, UpdateTimeEntryInput],
      [Result_2],
      [],
    ),
  'updateUserNotificationSettings' : IDL.Func(
      [UserNotificationSettings],
      [Result_1],
      [],
    ),
  'updateVacationBalance' : IDL.Func(
      [EmployeeId, IDL.Text, UpdateVacationBalanceInput],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AbsenceId = IDL.Nat;
  const AbsenceStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AbsenceTypeId = IDL.Nat;
  const Timestamp = IDL.Int;
  const EmployeeId = IDL.Nat;
  const CompanyId = IDL.Nat;
  const Absence = IDL.Record({
    'id' : AbsenceId,
    'status' : AbsenceStatus,
    'absenceTypeId' : AbsenceTypeId,
    'dateTo' : IDL.Text,
    'ganztaetig' : IDL.Bool,
    'approvedBy' : IDL.Opt(IDL.Principal),
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'employeeId' : EmployeeId,
    'resetReason' : IDL.Opt(IDL.Text),
    'rejectionComment' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Text,
    'dauer' : IDL.Nat,
    'companyId' : CompanyId,
  });
  const Result_15 = IDL.Variant({ 'ok' : Absence, 'err' : IDL.Text });
  const ExpenseId = IDL.Nat;
  const ExpenseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExpenseTypeId = IDL.Nat;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'status' : ExpenseStatus,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
    'resetReason' : IDL.Opt(IDL.Text),
    'billableCHF' : IDL.Float64,
    'reimbursementCHF' : IDL.Float64,
    'expenseTypeId' : ExpenseTypeId,
    'receiptBlobId' : IDL.Opt(IDL.Text),
    'companyId' : CompanyId,
  });
  const Result_8 = IDL.Variant({ 'ok' : Expense, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectId = IDL.Nat;
  const ProjectAssignment = IDL.Record({
    'employeeId' : EmployeeId,
    'projectId' : ProjectId,
    'companyId' : CompanyId,
  });
  const Result_26 = IDL.Variant({ 'ok' : ProjectAssignment, 'err' : IDL.Text });
  const CreateAbsenceInput = IDL.Record({
    'absenceTypeId' : AbsenceTypeId,
    'dateTo' : IDL.Text,
    'ganztaetig' : IDL.Bool,
    'description' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Text,
    'dauer' : IDL.Nat,
  });
  const CreateAbsenceTypeInput = IDL.Record({
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Text,
    'requiresApproval' : IDL.Bool,
    'compensated' : IDL.Bool,
  });
  const AbsenceType = IDL.Record({
    'id' : AbsenceTypeId,
    'aktiv' : IDL.Bool,
    'name' : IDL.Text,
    'requiresApproval' : IDL.Bool,
    'compensated' : IDL.Bool,
    'companyId' : CompanyId,
  });
  const Result_14 = IDL.Variant({ 'ok' : AbsenceType, 'err' : IDL.Text });
  const Rechnungsadresse = IDL.Record({
    'ort' : IDL.Opt(IDL.Text),
    'plz' : IDL.Opt(IDL.Text),
    'zusatz1' : IDL.Opt(IDL.Text),
    'zusatz2' : IDL.Opt(IDL.Text),
    'postfach' : IDL.Opt(IDL.Text),
    'land' : IDL.Text,
    'strasse' : IDL.Opt(IDL.Text),
  });
  const KundeZeiterfassungsart = IDL.Variant({
    'stuendlich' : IDL.Null,
    'block' : IDL.Null,
  });
  const CreateCustomerInput = IDL.Record({
    'rechnungsadresse' : IDL.Opt(Rechnungsadresse),
    'contact' : IDL.Opt(IDL.Text),
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Text,
    'zeiterfassungsart' : IDL.Opt(KundeZeiterfassungsart),
    'kundennummer' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'beschreibung' : IDL.Opt(IDL.Text),
    'waehrung' : IDL.Opt(IDL.Text),
  });
  const CustomerId = IDL.Nat;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'rechnungsadresse' : IDL.Opt(Rechnungsadresse),
    'contact' : IDL.Opt(IDL.Text),
    'aktiv' : IDL.Bool,
    'name' : IDL.Text,
    'zeiterfassungsart' : KundeZeiterfassungsart,
    'kundennummer' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'beschreibung' : IDL.Opt(IDL.Text),
    'waehrung' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Result_11 = IDL.Variant({ 'ok' : Customer, 'err' : IDL.Text });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'employee' : IDL.Null,
  });
  const EmploymentType = IDL.Variant({
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
    'contractor' : IDL.Null,
  });
  const CreateEmployeeInput = IDL.Record({
    'ort' : IDL.Opt(IDL.Text),
    'plz' : IDL.Opt(IDL.Text),
    'weeklyHoursTarget' : IDL.Float64,
    'postfach' : IDL.Opt(IDL.Text),
    'land' : IDL.Opt(IDL.Text),
    'role' : Role,
    'email' : IDL.Text,
    'geburtsdatum' : IDL.Opt(IDL.Int),
    'employmentType' : EmploymentType,
    'adresseZusatz1' : IDL.Opt(IDL.Text),
    'adresseZusatz2' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Text,
    'strasse' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'ort' : IDL.Opt(IDL.Text),
    'plz' : IDL.Opt(IDL.Text),
    'weeklyHoursTarget' : IDL.Float64,
    'active' : IDL.Bool,
    'postfach' : IDL.Opt(IDL.Text),
    'land' : IDL.Opt(IDL.Text),
    'role' : Role,
    'email' : IDL.Text,
    'geburtsdatum' : IDL.Opt(IDL.Int),
    'employmentType' : EmploymentType,
    'adresseZusatz1' : IDL.Opt(IDL.Text),
    'adresseZusatz2' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Text,
    'principalId' : IDL.Opt(IDL.Principal),
    'strasse' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Text,
    'companyId' : CompanyId,
    'firstName' : IDL.Text,
  });
  const Result_10 = IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text });
  const FeiertagsberechnungsartType = IDL.Variant({
    'exaktWochentag' : IDL.Null,
    'entschaedigt' : IDL.Null,
    'exakt' : IDL.Null,
    'prozentual' : IDL.Null,
  });
  const CreateEmploymentInput = IDL.Record({
    'bis' : IDL.Opt(IDL.Int),
    'von' : IDL.Int,
    'pensum' : IDL.Float64,
    'feiertagsberechnungsart' : FeiertagsberechnungsartType,
    'stundenDi' : IDL.Nat,
    'stundenDo' : IDL.Nat,
    'stundenFr' : IDL.Nat,
    'stundenMi' : IDL.Nat,
    'stundenMo' : IDL.Nat,
    'stundenSa' : IDL.Nat,
    'stundenSo' : IDL.Nat,
    'funktion' : IDL.Text,
  });
  const Employment = IDL.Record({
    'id' : IDL.Text,
    'bis' : IDL.Opt(IDL.Int),
    'von' : IDL.Int,
    'pensum' : IDL.Float64,
    'feiertagsberechnungsart' : FeiertagsberechnungsartType,
    'stundenDi' : IDL.Nat,
    'stundenDo' : IDL.Nat,
    'stundenFr' : IDL.Nat,
    'stundenMi' : IDL.Nat,
    'stundenMo' : IDL.Nat,
    'stundenSa' : IDL.Nat,
    'stundenSo' : IDL.Nat,
    'employeeId' : EmployeeId,
    'funktion' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Result_9 = IDL.Variant({ 'ok' : Employment, 'err' : IDL.Text });
  const CreateExpenseInput = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'billableCHF' : IDL.Float64,
    'reimbursementCHF' : IDL.Float64,
    'expenseTypeId' : ExpenseTypeId,
    'receiptBlobId' : IDL.Opt(IDL.Text),
  });
  const CreateExpenseTypeInput = IDL.Record({
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Text,
    'billable' : IDL.Bool,
    'reimbursable' : IDL.Bool,
  });
  const ExpenseType = IDL.Record({
    'id' : ExpenseTypeId,
    'aktiv' : IDL.Bool,
    'name' : IDL.Text,
    'billable' : IDL.Bool,
    'reimbursable' : IDL.Bool,
    'companyId' : CompanyId,
  });
  const Result_7 = IDL.Variant({ 'ok' : ExpenseType, 'err' : IDL.Text });
  const CreateHolidayInput = IDL.Record({
    'ganztaegig' : IDL.Opt(IDL.Bool),
    'date' : IDL.Text,
    'name' : IDL.Text,
  });
  const HolidayId = IDL.Nat;
  const Holiday = IDL.Record({
    'id' : HolidayId,
    'ganztaegig' : IDL.Bool,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Result_6 = IDL.Variant({ 'ok' : Holiday, 'err' : IDL.Text });
  const ProjectStatus = IDL.Variant({
    'aktiv' : IDL.Null,
    'inaktiv' : IDL.Null,
    'abgeschlossen' : IDL.Null,
  });
  const Erfassungsart = IDL.Variant({
    'zeitBlock' : IDL.Null,
    'dauer' : IDL.Null,
  });
  const CreateProjectInput = IDL.Record({
    'status' : IDL.Opt(ProjectStatus),
    'erfassungsart' : IDL.Opt(Erfassungsart),
    'code' : IDL.Text,
    'billableRate' : IDL.Float64,
    'name' : IDL.Text,
    'customerId' : CustomerId,
    'kurzbezeichnung' : IDL.Text,
    'projektleiter' : IDL.Opt(EmployeeId),
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'erfassungsart' : IDL.Opt(Erfassungsart),
    'active' : IDL.Bool,
    'code' : IDL.Text,
    'billableRate' : IDL.Float64,
    'name' : IDL.Text,
    'customerId' : CustomerId,
    'kurzbezeichnung' : IDL.Text,
    'projektleiter' : IDL.Opt(EmployeeId),
    'companyId' : CompanyId,
  });
  const Result_5 = IDL.Variant({ 'ok' : Project, 'err' : IDL.Text });
  const CreateServiceTypeInput = IDL.Record({
    'defaultRate' : IDL.Float64,
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Text,
    'billable' : IDL.Bool,
  });
  const ServiceTypeId = IDL.Nat;
  const ServiceType = IDL.Record({
    'id' : ServiceTypeId,
    'defaultRate' : IDL.Float64,
    'aktiv' : IDL.Bool,
    'name' : IDL.Text,
    'billable' : IDL.Bool,
    'companyId' : CompanyId,
  });
  const Result_4 = IDL.Variant({ 'ok' : ServiceType, 'err' : IDL.Text });
  const CreateTimeBalanceCorrectionInput = IDL.Record({
    'typ' : IDL.Variant({ 'gutschrift' : IDL.Null, 'reduktion' : IDL.Null }),
    'ueberzeit' : IDL.Int,
    'bemerkung' : IDL.Text,
    'wirkungsdatum' : IDL.Int,
    'dauer' : IDL.Int,
  });
  const TimeBalanceCorrection = IDL.Record({
    'id' : IDL.Text,
    'typ' : IDL.Variant({ 'gutschrift' : IDL.Null, 'reduktion' : IDL.Null }),
    'ueberzeit' : IDL.Int,
    'bemerkung' : IDL.Text,
    'employeeId' : EmployeeId,
    'wirkungsdatum' : IDL.Int,
    'dauer' : IDL.Int,
    'companyId' : CompanyId,
  });
  const Result_3 = IDL.Variant({
    'ok' : TimeBalanceCorrection,
    'err' : IDL.Text,
  });
  const CreateTimeEntryInput = IDL.Record({
    'bis' : IDL.Opt(IDL.Text),
    'von' : IDL.Opt(IDL.Text),
    'hours' : IDL.Float64,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'billable' : IDL.Bool,
    'projectId' : ProjectId,
    'serviceTypeId' : ServiceTypeId,
  });
  const TimeEntryId = IDL.Nat;
  const TimeEntry = IDL.Record({
    'id' : TimeEntryId,
    'bis' : IDL.Opt(IDL.Text),
    'von' : IDL.Opt(IDL.Text),
    'hours' : IDL.Float64,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
    'billable' : IDL.Bool,
    'projectId' : ProjectId,
    'serviceTypeId' : ServiceTypeId,
    'companyId' : CompanyId,
  });
  const Result_2 = IDL.Variant({ 'ok' : TimeEntry, 'err' : IDL.Text });
  const CreateVacationBalanceInput = IDL.Record({
    'verfallsdatum' : IDL.Opt(IDL.Int),
    'kalenderjahr' : IDL.Int,
    'dauer' : IDL.Int,
  });
  const VacationBalance = IDL.Record({
    'id' : IDL.Text,
    'verfallsdatum' : IDL.Opt(IDL.Int),
    'employeeId' : EmployeeId,
    'kalenderjahr' : IDL.Int,
    'dauer' : IDL.Int,
    'companyId' : CompanyId,
  });
  const Result = IDL.Variant({ 'ok' : VacationBalance, 'err' : IDL.Text });
  const Result_16 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_25 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const CalendarData = IDL.Record({
    'absences' : IDL.Vec(Absence),
    'expenses' : IDL.Vec(Expense),
    'timeEntries' : IDL.Vec(TimeEntry),
  });
  const CompanySettings = IDL.Record({
    'timezone' : IDL.Text,
    'approvalRequired' : IDL.Bool,
    'allowExpiredVacationBalance' : IDL.Bool,
    'emailNewVacationRequest' : IDL.Bool,
    'emailOnApproval' : IDL.Bool,
    'vacationCarryoverDays' : IDL.Nat,
    'maxVacationDays' : IDL.Nat,
    'companyId' : CompanyId,
  });
  const Result_12 = IDL.Variant({ 'ok' : CompanySettings, 'err' : IDL.Text });
  const DashboardStats = IDL.Record({
    'hoursTarget' : IDL.Float64,
    'pendingExpenses' : IDL.Nat,
    'hoursThisWeek' : IDL.Float64,
    'remainingVacationMinutes' : IDL.Int,
    'approvedVacationDays' : IDL.Nat,
    'pendingVacations' : IDL.Nat,
  });
  const WorkTimeBalance = IDL.Record({
    'istStunden' : IDL.Int,
    'ueberzeit' : IDL.Int,
    'saldo' : IDL.Int,
    'periodEnd' : IDL.Text,
    'periodStart' : IDL.Text,
    'sollStunden' : IDL.Int,
    'korrektionen' : IDL.Int,
  });
  const Result_24 = IDL.Variant({ 'ok' : WorkTimeBalance, 'err' : IDL.Text });
  const Result_23 = IDL.Variant({
    'ok' : IDL.Opt(Employment),
    'err' : IDL.Text,
  });
  const Company = IDL.Record({
    'id' : CompanyId,
    'taxId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'logoUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
  });
  const Result_13 = IDL.Variant({ 'ok' : Company, 'err' : IDL.Text });
  const StandardTimeBlock = IDL.Record({ 'bis' : IDL.Text, 'von' : IDL.Text });
  const Standardarbeitszeiten = IDL.Record({
    'tuesday' : IDL.Vec(StandardTimeBlock),
    'wednesday' : IDL.Vec(StandardTimeBlock),
    'saturday' : IDL.Vec(StandardTimeBlock),
    'thursday' : IDL.Vec(StandardTimeBlock),
    'sunday' : IDL.Vec(StandardTimeBlock),
    'friday' : IDL.Vec(StandardTimeBlock),
    'monday' : IDL.Vec(StandardTimeBlock),
  });
  const Result_21 = IDL.Variant({
    'ok' : Standardarbeitszeiten,
    'err' : IDL.Text,
  });
  const ProjectMemberAssignment = IDL.Record({
    'stundensatz' : IDL.Float64,
    'employeeId' : EmployeeId,
    'serviceTypeId' : ServiceTypeId,
  });
  const Result_22 = IDL.Variant({
    'ok' : IDL.Vec(ProjectMemberAssignment),
    'err' : IDL.Text,
  });
  const ReportFilter = IDL.Record({
    'dateTo' : IDL.Text,
    'employeeId' : IDL.Opt(EmployeeId),
    'projectId' : IDL.Opt(ProjectId),
    'customerId' : IDL.Opt(CompanyId),
    'dateFrom' : IDL.Text,
  });
  const ReportData = IDL.Record({
    'expenses' : IDL.Float64,
    'entries' : IDL.Vec(TimeEntry),
    'billableHours' : IDL.Float64,
    'expenseItems' : IDL.Vec(Expense),
  });
  const Result_20 = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
  const UserNotificationSettings = IDL.Record({
    'emailNewVacationRequest' : IDL.Bool,
    'emailOnApproval' : IDL.Bool,
    'principalId' : IDL.Principal,
    'companyId' : CompanyId,
  });
  const Result_1 = IDL.Variant({
    'ok' : UserNotificationSettings,
    'err' : IDL.Text,
  });
  const AbsenceFilter = IDL.Record({
    'status' : IDL.Opt(AbsenceStatus),
    'absenceTypeId' : IDL.Opt(AbsenceTypeId),
    'dateTo' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Opt(EmployeeId),
    'dateFrom' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'oldStatus' : IDL.Text,
    'action' : IDL.Text,
    'changedBy' : IDL.Principal,
    'timestamp' : Time,
    'targetType' : IDL.Text,
    'newStatus' : IDL.Text,
    'targetId' : IDL.Nat,
    'previousApprovedBy' : IDL.Opt(IDL.Principal),
    'reason' : IDL.Opt(IDL.Text),
  });
  const Result_19 = IDL.Variant({
    'ok' : IDL.Vec(Employment),
    'err' : IDL.Text,
  });
  const ExpenseFilter = IDL.Record({
    'status' : IDL.Opt(ExpenseStatus),
    'dateTo' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Opt(EmployeeId),
    'dateFrom' : IDL.Opt(IDL.Text),
  });
  const Result_18 = IDL.Variant({
    'ok' : IDL.Vec(TimeBalanceCorrection),
    'err' : IDL.Text,
  });
  const TimeEntryFilter = IDL.Record({
    'dateTo' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Opt(EmployeeId),
    'projectId' : IDL.Opt(ProjectId),
    'dateFrom' : IDL.Opt(IDL.Text),
  });
  const Result_17 = IDL.Variant({
    'ok' : IDL.Vec(VacationBalance),
    'err' : IDL.Text,
  });
  const UpdateAbsenceInput = IDL.Record({
    'dateTo' : IDL.Opt(IDL.Text),
    'ganztaetig' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Opt(IDL.Text),
    'dauer' : IDL.Opt(IDL.Nat),
  });
  const UpdateAbsenceTypeInput = IDL.Record({
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'requiresApproval' : IDL.Opt(IDL.Bool),
    'compensated' : IDL.Opt(IDL.Bool),
  });
  const UpdateCompanyInput = IDL.Record({
    'taxId' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'logoUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
  });
  const UpdateCustomerInput = IDL.Record({
    'rechnungsadresse' : IDL.Opt(Rechnungsadresse),
    'contact' : IDL.Opt(IDL.Text),
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'zeiterfassungsart' : IDL.Opt(KundeZeiterfassungsart),
    'kundennummer' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'beschreibung' : IDL.Opt(IDL.Text),
    'waehrung' : IDL.Opt(IDL.Text),
  });
  const UpdateEmployeeInput = IDL.Record({
    'ort' : IDL.Opt(IDL.Text),
    'plz' : IDL.Opt(IDL.Text),
    'weeklyHoursTarget' : IDL.Opt(IDL.Float64),
    'active' : IDL.Opt(IDL.Bool),
    'postfach' : IDL.Opt(IDL.Text),
    'land' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(Role),
    'email' : IDL.Opt(IDL.Text),
    'geburtsdatum' : IDL.Opt(IDL.Int),
    'employmentType' : IDL.Opt(EmploymentType),
    'adresseZusatz1' : IDL.Opt(IDL.Text),
    'adresseZusatz2' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Opt(IDL.Text),
    'strasse' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Opt(IDL.Text),
  });
  const UpdateEmploymentInput = IDL.Record({
    'bis' : IDL.Opt(IDL.Int),
    'von' : IDL.Opt(IDL.Int),
    'pensum' : IDL.Float64,
    'feiertagsberechnungsart' : IDL.Opt(FeiertagsberechnungsartType),
    'stundenDi' : IDL.Nat,
    'stundenDo' : IDL.Nat,
    'stundenFr' : IDL.Nat,
    'stundenMi' : IDL.Nat,
    'stundenMo' : IDL.Nat,
    'stundenSa' : IDL.Nat,
    'stundenSo' : IDL.Nat,
    'funktion' : IDL.Opt(IDL.Text),
  });
  const UpdateExpenseInput = IDL.Record({
    'date' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'billableCHF' : IDL.Opt(IDL.Float64),
    'reimbursementCHF' : IDL.Opt(IDL.Float64),
    'expenseTypeId' : IDL.Opt(ExpenseTypeId),
    'receiptBlobId' : IDL.Opt(IDL.Text),
  });
  const UpdateExpenseTypeInput = IDL.Record({
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'billable' : IDL.Opt(IDL.Bool),
    'reimbursable' : IDL.Opt(IDL.Bool),
  });
  const UpdateHolidayInput = IDL.Record({
    'ganztaegig' : IDL.Opt(IDL.Bool),
    'date' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
  });
  const UpdateProjectInput = IDL.Record({
    'status' : IDL.Opt(ProjectStatus),
    'erfassungsart' : IDL.Opt(Erfassungsart),
    'active' : IDL.Opt(IDL.Bool),
    'code' : IDL.Opt(IDL.Text),
    'billableRate' : IDL.Opt(IDL.Float64),
    'name' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Opt(CustomerId),
    'kurzbezeichnung' : IDL.Opt(IDL.Text),
    'projektleiter' : IDL.Opt(EmployeeId),
  });
  const UpdateServiceTypeInput = IDL.Record({
    'defaultRate' : IDL.Opt(IDL.Float64),
    'aktiv' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'billable' : IDL.Opt(IDL.Bool),
  });
  const UpdateTimeBalanceCorrectionInput = IDL.Record({
    'typ' : IDL.Opt(
      IDL.Variant({ 'gutschrift' : IDL.Null, 'reduktion' : IDL.Null })
    ),
    'ueberzeit' : IDL.Opt(IDL.Int),
    'bemerkung' : IDL.Opt(IDL.Text),
    'wirkungsdatum' : IDL.Opt(IDL.Int),
    'dauer' : IDL.Opt(IDL.Int),
  });
  const UpdateTimeEntryInput = IDL.Record({
    'bis' : IDL.Opt(IDL.Text),
    'von' : IDL.Opt(IDL.Text),
    'hours' : IDL.Opt(IDL.Float64),
    'date' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'billable' : IDL.Opt(IDL.Bool),
    'projectId' : IDL.Opt(ProjectId),
    'serviceTypeId' : IDL.Opt(ServiceTypeId),
  });
  const UpdateVacationBalanceInput = IDL.Record({
    'verfallsdatum' : IDL.Opt(IDL.Int),
    'kalenderjahr' : IDL.Opt(IDL.Int),
    'dauer' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveAbsence' : IDL.Func([AbsenceId], [Result_15], []),
    'approveExpense' : IDL.Func([ExpenseId], [Result_8], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignEmployeeToProject' : IDL.Func(
        [EmployeeId, ProjectId],
        [Result_26],
        [],
      ),
    'createAbsence' : IDL.Func([CreateAbsenceInput], [Result_15], []),
    'createAbsenceType' : IDL.Func([CreateAbsenceTypeInput], [Result_14], []),
    'createCustomer' : IDL.Func([CreateCustomerInput], [Result_11], []),
    'createEmployee' : IDL.Func([CreateEmployeeInput], [Result_10], []),
    'createEmployment' : IDL.Func(
        [EmployeeId, CreateEmploymentInput],
        [Result_9],
        [],
      ),
    'createExpense' : IDL.Func([CreateExpenseInput], [Result_8], []),
    'createExpenseType' : IDL.Func([CreateExpenseTypeInput], [Result_7], []),
    'createHoliday' : IDL.Func([CreateHolidayInput], [Result_6], []),
    'createProject' : IDL.Func([CreateProjectInput], [Result_5], []),
    'createServiceType' : IDL.Func([CreateServiceTypeInput], [Result_4], []),
    'createTimeBalanceCorrection' : IDL.Func(
        [EmployeeId, CreateTimeBalanceCorrectionInput],
        [Result_3],
        [],
      ),
    'createTimeEntry' : IDL.Func([CreateTimeEntryInput], [Result_2], []),
    'createVacationBalance' : IDL.Func(
        [EmployeeId, CreateVacationBalanceInput],
        [Result],
        [],
      ),
    'deleteAbsence' : IDL.Func([AbsenceId], [Result_16], []),
    'deleteAbsenceType' : IDL.Func([AbsenceTypeId], [Result_16], []),
    'deleteCustomer' : IDL.Func([CustomerId], [Result_16], []),
    'deleteEmployee' : IDL.Func([EmployeeId], [Result_16], []),
    'deleteEmployment' : IDL.Func([EmployeeId, IDL.Text], [Result_16], []),
    'deleteExpense' : IDL.Func([ExpenseId], [Result_16], []),
    'deleteExpenseType' : IDL.Func([ExpenseTypeId], [Result_16], []),
    'deleteHoliday' : IDL.Func([HolidayId], [Result_16], []),
    'deleteProject' : IDL.Func([ProjectId], [Result_16], []),
    'deleteServiceType' : IDL.Func([ServiceTypeId], [Result_16], []),
    'deleteTimeBalanceCorrection' : IDL.Func(
        [EmployeeId, IDL.Text],
        [Result_16],
        [],
      ),
    'deleteTimeEntry' : IDL.Func([TimeEntryId], [Result_16], []),
    'deleteVacationBalance' : IDL.Func([EmployeeId, IDL.Text], [Result_16], []),
    'generateInviteCode' : IDL.Func([EmployeeId], [Result_25], []),
    'getCalendarEntries' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [CalendarData],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanySettings' : IDL.Func([], [Result_12], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEmployeeWorkTimeBalance' : IDL.Func(
        [EmployeeId, IDL.Text, IDL.Text],
        [Result_24],
        ['query'],
      ),
    'getEmployeeWorkTimeBalanceFromStart' : IDL.Func(
        [EmployeeId],
        [Result_24],
        ['query'],
      ),
    'getEmploymentForDate' : IDL.Func(
        [EmployeeId, IDL.Text],
        [Result_23],
        ['query'],
      ),
    'getMyCompany' : IDL.Func([], [Result_13], ['query']),
    'getMyEmployee' : IDL.Func([], [Result_10], ['query']),
    'getMyStandardarbeitszeiten' : IDL.Func([], [Result_21], ['query']),
    'getProjectMembers' : IDL.Func([ProjectId], [Result_22], ['query']),
    'getReportData' : IDL.Func([ReportFilter], [ReportData], ['query']),
    'getStandardarbeitszeitenForEmployee' : IDL.Func(
        [EmployeeId],
        [Result_21],
        ['query'],
      ),
    'getTimeBalance' : IDL.Func([EmployeeId], [Result_20], ['query']),
    'getUserNotificationSettings' : IDL.Func([], [Result_1], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listAbsenceTypes' : IDL.Func([], [IDL.Vec(AbsenceType)], ['query']),
    'listAbsences' : IDL.Func([AbsenceFilter], [IDL.Vec(Absence)], ['query']),
    'listAuditLog' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listEmployments' : IDL.Func([EmployeeId], [Result_19], ['query']),
    'listExpenseTypes' : IDL.Func([], [IDL.Vec(ExpenseType)], ['query']),
    'listExpenses' : IDL.Func([ExpenseFilter], [IDL.Vec(Expense)], ['query']),
    'listHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'listProjectAssignments' : IDL.Func(
        [],
        [IDL.Vec(ProjectAssignment)],
        ['query'],
      ),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listServiceTypes' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
    'listTimeBalanceCorrections' : IDL.Func(
        [EmployeeId],
        [Result_18],
        ['query'],
      ),
    'listTimeEntries' : IDL.Func(
        [TimeEntryFilter],
        [IDL.Vec(TimeEntry)],
        ['query'],
      ),
    'listVacationBalances' : IDL.Func([EmployeeId], [Result_17], ['query']),
    'redeemInviteCode' : IDL.Func([IDL.Text], [Result_10], []),
    'registerCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_13],
        [],
      ),
    'rejectAbsence' : IDL.Func([AbsenceId, IDL.Text], [Result_15], []),
    'rejectExpense' : IDL.Func([ExpenseId, IDL.Opt(IDL.Text)], [Result_8], []),
    'removeEmployeeFromProject' : IDL.Func(
        [EmployeeId, ProjectId],
        [Result_16],
        [],
      ),
    'resetAbsenceToAusstehend' : IDL.Func(
        [AbsenceId, IDL.Text],
        [Result_15],
        [],
      ),
    'resetExpenseToAusstehend' : IDL.Func(
        [ExpenseId, IDL.Text],
        [Result_8],
        [],
      ),
    'revokeInviteCode' : IDL.Func([IDL.Text], [Result_16], []),
    'setMyStandardarbeitszeiten' : IDL.Func(
        [Standardarbeitszeiten],
        [Result_16],
        [],
      ),
    'setProjectMembers' : IDL.Func(
        [ProjectId, IDL.Vec(ProjectMemberAssignment)],
        [Result_16],
        [],
      ),
    'setStandardarbeitszeitenForEmployee' : IDL.Func(
        [EmployeeId, Standardarbeitszeiten],
        [Result_16],
        [],
      ),
    'updateAbsence' : IDL.Func(
        [AbsenceId, UpdateAbsenceInput],
        [Result_15],
        [],
      ),
    'updateAbsenceType' : IDL.Func(
        [AbsenceTypeId, UpdateAbsenceTypeInput],
        [Result_14],
        [],
      ),
    'updateCompany' : IDL.Func([UpdateCompanyInput], [Result_13], []),
    'updateCompanySettings' : IDL.Func([CompanySettings], [Result_12], []),
    'updateCustomer' : IDL.Func(
        [CustomerId, UpdateCustomerInput],
        [Result_11],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [EmployeeId, UpdateEmployeeInput],
        [Result_10],
        [],
      ),
    'updateEmployment' : IDL.Func(
        [EmployeeId, IDL.Text, UpdateEmploymentInput],
        [Result_9],
        [],
      ),
    'updateExpense' : IDL.Func([ExpenseId, UpdateExpenseInput], [Result_8], []),
    'updateExpenseType' : IDL.Func(
        [ExpenseTypeId, UpdateExpenseTypeInput],
        [Result_7],
        [],
      ),
    'updateHoliday' : IDL.Func([HolidayId, UpdateHolidayInput], [Result_6], []),
    'updateProject' : IDL.Func([ProjectId, UpdateProjectInput], [Result_5], []),
    'updateServiceType' : IDL.Func(
        [ServiceTypeId, UpdateServiceTypeInput],
        [Result_4],
        [],
      ),
    'updateTimeBalanceCorrection' : IDL.Func(
        [EmployeeId, IDL.Text, UpdateTimeBalanceCorrectionInput],
        [Result_3],
        [],
      ),
    'updateTimeEntry' : IDL.Func(
        [TimeEntryId, UpdateTimeEntryInput],
        [Result_2],
        [],
      ),
    'updateUserNotificationSettings' : IDL.Func(
        [UserNotificationSettings],
        [Result_1],
        [],
      ),
    'updateVacationBalance' : IDL.Func(
        [EmployeeId, IDL.Text, UpdateVacationBalanceInput],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };